### ISSUE TITLE
Decoding SSB with airspy

### ISSUE THREAD

**Issue by jrobinson-uk** [simonyiszk/csdr#13]
Using the example on the README I created a line to use airspy_rx and achieve a similar result:

airspy_rx -t 0 -r /dev/stdout -a 1 -f 434.253 -g 18  | csdr fir_decimate_cc 59 0.005 HAMMING | csdr bandpass_fir_fft_cc 0 0.1 0.05 | csdr realpart_cf | csdr agc_ff | csdr limit_ff | csdr convert_f_s16 | mplayer -ao jack:name=RTTY -cache 1024 -quiet -rawaudio samplesize=2:channels=1:rate=48000 -demuxer rawaudio -&

I don't really understand what each part is doing but signal sounds correct, however there are occasional pauses in the signal which make it really hard to decode. Is there anything in this command which could cause this.

Runnning on Raspberry Pi 3

**Comment by ha7ilm** [comment]
Hi James,

The sampling rate of the signal output by `airspy_rx` is 2.5 Msps with the `-a1` switch. 
The signal should be correctly resampled so that at the end of the chain, the sampling rate matches with the audio card's output rate (48 ksps). 

The output of `fir_decimate_cc` is 42372 sps (2500000/59)
The passband of `bandpass_fir_fft_cc˛` is: 0..4237 Hz

To match this signal to the 48000 sps input of `mplayer`, you will need a resampler. I advise you to:

* use 48 as the decimation factor for `fir_decimate_cc`,
* use `csdr fractional_decimator_cc 0.9984191` to be totally accurate, although it may work without it. 

The new command is:

    airspy_rx -t 0 -r /dev/stdout -a 1 -f 434.253 -g 18 | csdr fir_decimate_cc 48 0.005 HAMMING | csdr bandpass_fir_fft_cc 0 0.1 0.05 | csdr realpart_cf | csdr agc_ff | csdr limit_ff | csdr fractional_decimator_cc 1.001583333333 | csdr convert_f_s16 | mplayer -ao jack:name=RTTY -cache 1024 -quiet -rawaudio samplesize=2:channels=1:rate=48000 -demuxer rawaudio -

**Comment by jrobinson-uk** [comment]
wow, brilliant I'll test tomorrow

**Comment by jrobinson-uk** [comment]
Didn't get to test today, however just checking isn't the sample rate for -a1 switch 3Msps with the airspy _mini_, I think it only support 3M & 6M. How would this impact on the command?

**Comment by ha7ilm** [comment]
airspy_rx -t 0 -r /dev/stdout -a 1 -f 434.253 -g 18 | csdr fir_decimate_cc 60 0.005 HAMMING | csdr bandpass_fir_fft_cc 0 0.1 0.05 | csdr realpart_cf | csdr agc_ff | csdr limit_ff | csdr fractional_decimator_cc 1.0416 | csdr convert_f_s16 | mplayer -ao jack:name=RTTY -cache 1024 -quiet -rawaudio samplesize=2:channels=1:rate=48000 -demuxer rawaudio -

**Comment by jrobinson-uk** [comment]
It doesn't like the `csdr fractional_decimator_cc 1.0416` line:

```
fir_decimate_cc: taps_length = 801
bandpass_fir_fft_cc: window = HAMMING
bandpass_fir_fft_cc: (fft_size = 256) = (taps_length = 79) + (input_size = 178) - 1
(overlap_length = 78) = taps_length - 1
csdr: function name given in argument 1 does not exist. Possible causes:
- You mistyped the commandline.
- You need to update csdr to a newer version (if available).

bandpass_fir_fft_cc: filter initialized, low_cut = 0, high_cut = 0.1```

**Comment by ha7ilm** [comment]
Oops.

        airspy_rx -t 0 -r /dev/stdout -a 1 -f 434.253 -g 18 | csdr fir_decimate_cc 60 0.005 HAMMING | csdr bandpass_fir_fft_cc 0 0.1 0.05 | csdr realpart_cf | csdr agc_ff | csdr limit_ff | csdr fractional_decimator_ff 1.0416 | csdr convert_f_s16 | mplayer -ao jack:name=RTTY -cache 1024 -quiet -rawaudio samplesize=2:channels=1:rate=48000 -demuxer rawaudio -

**Comment by jrobinson-uk** [comment]
Perfect, works on laptop, I'll try on Pi tomorrow

**Comment by ha7ilm** [comment]
Great!

**Comment by jrobinson-uk** [comment]
Hmmm,

Not immediately successful,  lots of caching errors 
`Cache not filling, consider increasing -cache and/or -cache-min!`

some breaks in the audio and even when smooth, can't be decoded in the same way output from pc can.

**Comment by ha7ilm** [comment]
Seems like lack of CPU time for this sample rate. 

Can you copy the output of `top`, while running the command above?

Also you could try this:

    airspy_rx -t 0 -r /dev/stdout -a 1 -f 434.253 -g 18 | csdr fir_decimate_cc 4 0.01 HAMMING | csdr fir_decimate_cc 15 0.001 HAMMING | csdr bandpass_fir_fft_cc 0 0.1 0.05 | csdr realpart_cf | csdr agc_ff | csdr limit_ff | csdr fractional_decimator_ff 1.0416 | csdr convert_f_s16 | mplayer -ao jack:name=RTTY -cache 1024 -quiet -rawaudio samplesize=2:channels=1:rate=48000 -demuxer rawaudio -

**Comment by jrobinson-uk** [comment]
![screenshot from 2016-07-30 21-25-27](https://cloud.githubusercontent.com/assets/4701504/17272942/3b3082a0-569c-11e6-82cd-85318cfd4d05.png)

**Comment by ha7ilm** [comment]
What is the console output if you enter this?

    airspy_rx -t 0 -r /dev/stdout -a 1 -f 434.253 -g 18 | csdr through > /dev/null

**Comment by ha7ilm** [comment]
Also airspy_rx takes a lot of CPU time. You could try if this one is better:

https://github.com/rxseger/rx_tools

You will also need:

https://github.com/pothosware/SoapyAirspy
https://github.com/pothosware/SoapySDR

**Comment by jrobinson-uk** [comment]
pi@raspberrypi:~ $ airspy_rx -t 0 -r /dev/stdout -a 1 -f 434.253 -g 18 | csdr through > /dev/null
through: 22330356 bytes/s 5504
through: 22317058 bytes/s 11008
through: 22312894 bytes/s 16384
through: 22857612 bytes/s 22400
through: 22776752 bytes/s 27904
through: 22730330 bytes/s 33408
through: 22839760 bytes/s 39040
through: 22967242 bytes/s 44858
through: 22887850 bytes/s 50304
through: 22847282 bytes/s 55808
through: 23016386 bytes/s 61824
through: 22969998 bytes/s 67328
through: 22931224 bytes/s 72832
through: 23055278 bytes/s 78848
through: 23016628 bytes/s 84352
through: 22985126 bytes/s 89856
through: 22954408 bytes/s 95360
through: 23050686 bytes/s 101376
through: 23021154 bytes/s 106880
through: 22913562 bytes/s 112000
through: 22974476 bytes/s 117888
through: 22945072 bytes/s 123264
through: 22934206 bytes/s 128781
through: 22919332 bytes/s 134400
through: 22995950 bytes/s 140416
through: 23004536 bytes/s 146025
through: 22983006 bytes/s 151552
through: 23056692 bytes/s 157696
through: 23049514 bytes/s 163200
through: 23041618 bytes/s 168832
through: 23106596 bytes/s 174976
through: 23098064 bytes/s 180480
through: 23089778 bytes/s 186112
through: 23082274 bytes/s 191616

I'll take a look at rx_tools, installing now

**Comment by ha7ilm** [comment]
You seem to get `23089778 / 4 (sizeof(float)) / 2 (complex signal) = 2886222` samples per second from the receiver in practice. Maybe if we recalculate everything with respect to that, it will be fine.

**Comment by ha7ilm** [comment]
What about this?

    airspy_rx -t 0 -r /dev/stdout -a 1 -f 434.253 -g 18 | csdr fir_decimate_cc 4 0.01 HAMMING | csdr fir_decimate_cc 15 0.001 HAMMING | csdr bandpass_fir_fft_cc 0 0.1 0.05 | csdr realpart_cf | csdr agc_ff | csdr limit_ff | csdr convert_f_s16 | mplayer -ao jack:name=RTTY -cache 1024 -quiet -rawaudio samplesize=2:channels=1:rate=48000 -demuxer rawaudio -

**Comment by jrobinson-uk** [comment]
Still really choppy, could the issue be with mplayer:
https://trac.mplayerhq.hu/ticket/2063

Are there alternative playback solutions?

**Comment by ha7ilm** [comment]
I would use `aplay`. 

    aplay -f S16_LE -r48000 -c2

**Comment by jrobinson-uk** [comment]
Okay when I run : 

`airspy_rx -t 0 -r /dev/stdout -a 1 -f 434.253 -g 18 | csdr fir_decimate_cc 4 0.01 HAMMING | csdr fir_decimate_cc 15 0.001 HAMMING | csdr bandpass_fir_fft_cc 0 0.1 0.05 | csdr realpart_cf | csdr agc_ff | csdr limit_ff | csdr convert_f_s16 | aplay -f S16_LE -r48000 -c2`

I get : 
`fir_decimate_cc: taps_length = 3999
fir_decimate_cc: taps_length = 401
taps_length = 3999
padded_taps_length = 4000
taps = 1f19018
taps = 1f19020
taps_length = 401
padded_taps_length = 408
taps = 1577018
taps = 1577020
bandpass_fir_fft_cc: window = HAMMING
bandpass_fir_fft_cc: (fft_size = 256) = (taps_length = 79) + (input_size = 178) - 1
(overlap_length = 78) = taps_length - 1
bandpass_fir_fft_cc: filter initialized, low_cut = 0, high_cut = 0.1
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
underrun!!! (at least 115.007 ms long)
underrun!!! (at least 16.915 ms long)
underrun!!! (at least 8.020 ms long)
underrun!!! (at least 7.919 ms long)
underrun!!! (at least 121.012 ms long)
underrun!!! (at least 14.916 ms long)
underrun!!! (at least 32.414 ms long)
underrun!!! (at least 116.171 ms long)`

still juttery, so I can't check the RTTY decode is correct.

If I run : 
`airspy_rx -t 0 -r /dev/stdout -a 1 -f 434.253 -g 18 | csdr fir_decimate_cc 4 0.01 HAMMING | csdr fir_decimate_cc 15 0.001 HAMMING | csdr bandpass_fir_fft_cc 0 0.1 0.05 | csdr realpart_cf | csdr agc_ff | csdr limit_ff | csdr convert_f_s16 >> test_audio`

and then

`cat test_audio | mplayer  -cache 4048 -quiet -rawaudio samplesize=2:channels=1:rate=48000 -demuxer rawaudio -` or pass through aplay i get a continous recording that plays back fine but doesn't decode.

**Comment by ha7ilm** [comment]
Add a `csdr fractional_decimator_ff` to have precise symbol timing for RTTY. Use these equations to calculate decimation ratios:

```
IF sample rate = input sample rate / decimation factor (fir_decimate_cc, this is an integer number)
audio sample rate = IF sample rate / decimation factor (fractional_decimator_ff, this is a floating point number)
```

**Comment by jrobinson-uk** [comment]
Ok I went back a few steps and actually found that a command from earlier actually worked really well:

`
airspy_rx -t 0 -r /dev/stdout -a 1 -f 434.178 -g 18 | csdr fir_decimate_cc 60 0.005 HAMMING | csdr bandpass_fir_fft_cc 0 0.1 0.05 | csdr realpart_cf | csdr agc_ff | csdr limit_ff | csdr fractional_decimator_ff 1.0416 | csdr convert_f_s16 | mplayer -cache 1024 -quiet -rawaudio samplesize=2:channels=1:rate=48000 -demuxer rawaudio -
`

It's now running smoothly (with the occasionally caching error) but I can decode 80% of the audio into telemetry data, wooo!

**Comment by ha7ilm** [comment]
Great!

**Comment by jrobinson-uk** [comment]
Thanks for all the help!!! :+1:
