### ISSUE TITLE
Decoding SSB with ELAD FDM-S2

### ISSUE THREAD

**Issue by michelinok** [simonyiszk/csdr#14]
Hi, can someone provide an example of demodulating LSB voice at an input samplerate of 192k  24 bit integer?
I find it quite difficult to build the string

I provide the input 192k i/ with this command:

 elad_sdr_24 14248800 0 

that output an infinite i/q stream at 192k on the frequency 14.248800kHz

Any help?

**Comment by michelinok** [comment]
Got something with this command ...but the audio is very metallic...ANY IDEA?

elad_sdr_24 7087000 0 | csdr convert_s24_f --bigendian | csdr shift_addition_cc 0.015625 | csdr fir_decimate_cc 4.35 0.005 HAMMING | csdr bandpass_fir_fft_cc -0.05 0 1 | csdr realpart_cf | csdr agc_ff | csdr limit_ff | csdr convert_f_s16 | mplayer -cache 1024 -quiet -rawaudio samplesize=2:channels=1:rate=44100 -demuxer rawaudio -

**Comment by michelinok** [comment]
i'm using a decimate of 4.35 because    pactl list short sinks   give me that i'm using 44.100kHz on the soundcard

**Comment by ha7ilm** [comment]
`fir_decimate_cc` will round that to 4.
Use `fractional_decimator_ff` as well in the chain.

**Comment by michelinok** [comment]
I'll try this morning and let you know.
Many thanks

Il 31 lug 2016 11:42, "András Retzler" <notifications@github.com> ha
scritto:

**Comment by michelinok** [comment]
ok...switched to Raspberry 3 with 48khz output...

./elad_sdr_24 7175000 0 | csdr convert_s24_f --bigendian | csdr fractional_decimator_ff  4 0.005 HAMMING | csdr bandpass_fir_fft_cc -0.05 0 1 | csdr realpart_cf | csdr agc_ff | csdr limit_ff | csdr convert_f_s16 | mplayer -cache 1024 -quiet -rawaudio samplesize=2:channels=1:rate=48000 -demuxer rawaudio -


The signal is lsb on 7175000  (having the samplerate of 192k, the decimator is exactly 4).

1) How can i select 3khz of bandwidth? cannot understand :°(
2) is the string ok?
