### ISSUE TITLE
Help creating a working chain...

### ISSUE THREAD

**Issue by michelinok** [simonyiszk/csdr#18]
Hi!
I'm fighting with my receiver and csd for months...and cannot find a valid "chain" of commands to decode some audio...
**My receiver outputs samples at a samplerate of 192khz 24 bit integer...**
What i would like to do is: tune the receiver to a central frequency (for example 7070000) and decode an lsb audio signal at 7073000 (so +3 khz from the tuned freq) with a bandwidth of 2.7khz (standard ham audio bandwidth).
The output of the soundcard is 44.100  (i'm using a raspberry 3 with the classic 3.5mm jack).
The receiver outputs samples in this way:
elad_sdr_24 7070000 0 | csdr...     (where frequency is 7070000 and 0 means infinite samples).

Can someone provide me the command to use?

Many thanks!

'73 de IU5HES

---

**Comment by ha7ilm** [comment]
I can't try it, anyway I guess that:

    elad_sdr_24 7070000 0 | csdr convert_s24_f | csdr shift_addition_cc $(python -c "print (7073000-7070000.)/192000") |  csdr fir_decimate_cc 4 0.05 HAMMING | csdr bandpass_fir_fft_cc -0.1 0 0.05 | csdr realpart_cf | csdr agc_ff | csdr limit_ff | csdr convert_f_s16 | mplayer -cache 1024 -quiet -rawaudio samplesize=2:channels=1:rate=48000 -demuxer rawaudio -

**Comment by ha7ilm** [comment]
There might as well be an endianness problem, which can be fixed with `csdr convert_s24_f --bigendian`.

**Comment by michelinok** [comment]
I'll try asap and let you know.
Please, can you explain where is the audio bandwidth calculated? (I mean
the 2.3 or 2.7 khz... cannot remember the ham standard)

=================
Http://www.iu5hes.it
=================

Il 09 ott 2016 20:42, "András Retzler" <notifications@github.com> ha
scritto:

I can't try it, anyway I guess that:

elad_sdr_24 7070000 0 | csdr convert_s24_f | csdr shift_addition_cc
$(python -c "print (7073000-7070000.)/192000") |  csdr fir_decimate_cc
4 0.05 HAMMING | csdr bandpass_fir_fft_cc -0.1 0 0.05 | csdr
realpart_cf | csdr agc_ff | csdr limit_ff | csdr convert_f_s16 |
mplayer -cache 1024 -quiet -rawaudio
samplesize=2:channels=1:rate=48000 -demuxer rawaudio -

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/simonyiszk/csdr/issues/18#issuecomment-252504208>, or mute
the thread

**Comment by ha7ilm** [comment]
csdr bandpass_fir_fft_cc -0.1 0 0.05

...will have around 4.8 kHz.

    csdr bandpass_fir_fft_cc -0.05625 0 0.002 

...will have 2.7 kHz, with a transition BW of 96 Hz.

**Comment by ha7ilm** [comment]
I hope it is solved by now.
