### ISSUE TITLE
Help editing Makefile

### ISSUE THREAD

**Issue by michelinok** [simonyiszk/csdr#20]
Hi!
Can someone help me modifing the Makefile for Raspberry?
Have not understood how should i change it...
Many thanks!
Michele

**Comment by ha7ilm** [comment]
Hi @michelinok,

The `Makefile` should work on the Raspberry. What is the exact error message you get?

**Comment by michelinok** [comment]
no errors, i tought that i had to change the makefile :) sorry for the misunderstanding...my english is not so good :)
