### ISSUE TITLE
Csdr (or Gnuradio) interfacing to RPITX

### ISSUE THREAD

**Issue by UgoPoddine** [simonyiszk/csdr#38]
Hello group,

I'm more and more bit confused regarding interfacing of GnuRadio with Evariste's RPITX, and I hope you can help.
I have used several test SSB flowgraph or CSDR tfor modulating in USB audio files and transmitting them over RPITX.
The situation is the following :

I'm using RPITX "standard version" (not the new one) installed on a RaspberryPI2 with Stretch (Linux 4.14.49+ #11201 armv6l GNU/Linux)
Test trasmission over RPITX on USB of sampleaudio.wav test file, modulated using the Evariste's modulation program pissb is successful over 10 m band
I made a test flowgraph on GnuRadio on Windows that reads the "modulated" (by pissb) wav file and send it to the RaspberryPI via UDP sink : this allows an RPITX correct transmission, but only if I use the following receaving statement :
nc -u -l 8011 | sudo rpitx -i - -m IQ -a 14 -f $FREQUENCY

Gnuradio reads in FLOAT format and send it to UDPsink in FLOAT format (not in COMPLEX)

If I start modulating the sampleaudio.wav using different USB TX flowgraph (I can share them, for example the one of oz9aec or of ha7ilm)  or also CSDR and I send the modulated output (correct, checking FFT scope...) to RPITX using again UDP sink, the result is a noise transmission (both setting RPITX in IQ or IQFLOAT format, both transmitting float or complex data flow over UDP sink.
Worst, the "correctly running" output of PISSB utility can be played o using any kind of playing audio tool, while the modulated output of the different flowgraphs (being IQ) should not.
I'm consequently a bit confused : what is the real data format accepted as input from RPITX, and which the correct way for interfacing it with Gnuradio and csdr ? (I guess that UDP or TCP sink - now deprecated - is not the issue...)

Any help appreciated
Regards, 73
Ugo

**Comment by ha7ilm** [comment]
Responded at `rpitx-app-note`.
