### ISSUE TITLE
Adding two signals

### ISSUE THREAD

**Issue by lu7did** [simonyiszk/csdr#44]
Hi,

I'm willing to add two signals. One baseband (say 500 KHz wide) I/Q stream coming from a rtl-sdr dongle and another signal, locally created, carrying some arbitrary modulation. The resulting baseband can be used to modulate using SSB an output signal.

Main purpose is to implement a linear transponder and adding some local telemetry channel.

I've been exploring the functions of csdr but found no function that can be used as a linear sum of two signals with proper alignment of sample rates.

¿Any idea?

73 de Pedro, LU7DID

**Comment by ha7ilm** [comment]
You can't add signals currently.

You can either use GNU Radio to do this on live signals or GNU Octave to do this on previously recorded signals.
