### ISSUE TITLE
FT8 decoding with Airspy HF+ Discovery

### ISSUE THREAD

**Issue by kholia** [simonyiszk/csdr#59]
FT8 decoding works well with RTL-SDR V3 Dongle:

```
$ ~/librtlsdr/src/rtl_sdr -s 1000000 -f 14074000 -g 20 -O dm=4:dm=20E6 - | csdr convert_u8_f | csdr fir_decimate_cc 250 0.00166665 HAMMING > /tmp/ft8_14074000.c2

$ ./ft8d backup/ft8_14074000.c2 
 00   2.6  -9 -0.15 14074124 VU3CER VU3FOE MK68   MK68
 00   3.8  -6 -0.15 14074424 VU3CER VU3FOE MK68   MK68
 00   3.1  -5 -0.15 14074523 VU3CER VU3FOE MK68   MK68
 00   3.3   3 -0.14 14074623 VU3CER VU3FOE MK68   MK68
 00   3.8  12 -0.13 14074723 VU3CER VU3FOE MK68   MK68
```

The `ft8d` binary comes from https://github.com/pavel-demin/ft8d project.

Next, I tried using Airspy HF+ Discovery instead of the RTL-SDR V3 Dongle.

```
$ airspyhf_rx -r /dev/stdout -a 384000 -f 14.074000 -g on -m on - | csdr fir_decimate_cc 80 0.00166665 HAMMING > /tmp/ft8_14074000.c2"

$ ./ft8d backup/ft8_14074000.c2
<no decodes>
```

https://github.com/airspy/airspyhf/blob/master/tools/src/airspyhf_rx.c <-- I am using this to grab the IQ samples. I am guessing that the output format is CF32 which is directly supported by `csdr` tools. I could be totally wrong here.

No luck here!

Next, I tried using the Airspy HF+ Discover with `rx_tools`.

```
$ rx_sdr -s 384000 -f 14074000 -I CF32 -F CF32 - | csdr fir_decimate_cc 80 0.00166665 HAMMING > /tmp/ft8_14074000.c2

$ ./ft8d backup/ft8_14074000.c2
<no decodes>
```

No luck here either.

To ensure that FT8 traffic in always on the air, I use my https://github.com/kholia/Easy-Digital-Beacons-v1 project to generate such test FT8 traffic.

I am trying to understand where the bug is. Am I using `csdr` correctly? Or is airspyhf_rx subtly different in its behavior compared to rtl_sdr?

Note: All software versions are freshly built from git repos.

Thanks for the help.

**Comment by kholia** [comment]
Related: https://github.com/airspy/airspyhf/issues/29 (has IQ samples + more information).

Related: http://sv3exp.blogspot.com/2019/09/decoding-ft8-in-with-any-sdr-like-usrp.html

**Comment by ha7ilm** [comment]
To debug these kind of things, you should check the signal at each stage with e.g. `fft_cc (...) --octave` or by manually analyzing the data. Nevertheless, it should be checked that the signal of interest is in the passband of the decimating FIR filter (in the 1/80 middle part of the spectrum in this case), and the gain of the SDR hardware should be set correctly.

**Comment by kholia** [comment]
Thank you for the debugging tips.

Adding a passband filter seems to have sorted out my problem!

```
$ cat airspy_ft8_768000_14074000.iq | ./csdr fir_decimate_cc 192 0.00166665 HAMMING | ./csdr bandpass_fir_fft_cc 0 0.8 0.05 > ft8_14074000.c2
fir_decimate_cc: taps_length = 2401
./csdr bandpass_fir_fft_cc: window = HAMMING
./csdr bandpass_fir_fft_cc: (fft_size = 256) = (taps_length = 79) + (input_size = 178) - 1
(overlap_length = 78) = taps_length - 1
./csdr bandpass_fir_fft_cc: filter initialized, low_cut = 0, high_cut = 0.8

$ dd if=/dev/zero bs=1440000 count=1 >> ft8_14074000.c2  # dirty hack to workaround problems associated with slightly shorter files
1+0 records in
1+0 records out
1440000 bytes (1.4 MB, 1.4 MiB) copied, 0.00381435 s, 378 MB/s

$ ft8d ft8_14074000.c2
 00   4.7  -3 -0.95 14074609 VU3CER VU3FOE MK68   MK68
 00   6.1   5 -0.94 14074709 VU3CER VU3FOE MK68   MK68
```

Reference: http://sv3exp.blogspot.com/2019/09/decoding-ft8-in-with-any-sdr-like-usrp.html

Success!

Thanks for the help again. I will start using the visualization based debugging technique from now on, and also learn a bit about DSP :)

The motivation behind this is to do FT8 decoding with minimal CPU resources, and to ultimately run on Android (which could be seen as a common 'universal' computer). All source + docs will be open-source soon.
