### ISSUE TITLE
Please use a SONAME for libcsdr

### ISSUE THREAD

**Issue by irl** [simonyiszk/csdr#9]
Hi,

To make it easier for others to build software using libcsdr, please use a SONAME to allow for tracking of the API/ABI.

"A shared object was identified in a library directory (a directory in the standard linker path) which doesn't have a SONAME. This is usually an error.

SONAMEs are set with something like gcc -Wl,-soname,libfoo.so.0, where 0 is the major version of the library. If your package uses libtool, then libtool invoked with the right options should be doing this."

Thanks,

**Comment by ha7ilm** [comment]
Right, done at commit d1c5628f5001918bf0dc70b7d1737afc90f51d85.
